SourceHanSans = base.loadFont("Fonts/Source Han San.otf")
SourceHanSans.setPixelsPerUnit(100)
TimesNewRoman = base.loadFont("Fonts/Times New Roman.ttf")
TimesNewRoman.setPixelsPerUnit(100)
VAGRoundedBT = base.loadFont("Fonts/VAG Rounded BT.ttf")
VAGRoundedBT.setPixelsPerUnit(100)
VAGRoundedStdLight = base.loadFont("Fonts/VAG Rounded Std Light.otf")
VAGRoundedStdLight.setPixelsPerUnit(100)
Default = base.loadFont(base.MainGlobals.DEFAULTFONTPATH)
Default.setPixelsPerUnit(100)
DefaultChinese = base.loadFont("Fonts/msyhl.ttc")