import os

ROOTDIRECTORY = os.getcwd()

WINDOWTITLE = "Panda 3D Base"
WINDOWSIZE = "800 600"
WINDOWORIGIN = "560 240"
WINDOWFIXED = "#t"
WINDOWUNDECORATED = "#f"
WINDOWSHOW = ""
TRACEBACKMSG = True
CACHEMODELS = False
CHANGEZONESEQUENCE = False

DEBUGENABLED = True

DEFAULTFONTPATH = "Fonts/VAG Rounded Std Light.otf"
DEFAULTBACKGROUNDCOLOR = (255, 255, 255)
DEFAULTTEXTFG = (0, 0, 0, 1)
